"""
Weekly planning logic for PaceIQ.
Determines when to generate plans and saves them to disk.
"""

import pathlib
from datetime import datetime, date
from typing import Tuple, Optional, Dict, Any, List

from profile import TEMPO_PROGRESSION, WEEKLY_SCHEDULE
from config import PACEIQ_DATA_DIR, PLANS_DIR, get_config


def get_current_week_number() -> Tuple[int, int]:
    """
    Return (iso_week_number, year) for today.
    Uses ISO week calendar (Monday = day 1, weeks are 1-53).
    """
    today = date.today()
    iso_cal = today.isocalendar()
    return iso_cal[1], iso_cal[0]  # (week_number, year)


def get_tempo_target_for_week(week_number: int) -> Dict[str, Any]:
    """
    Return the tempo pace and HR targets for a given week number.
    If the week exceeds the defined progression, returns the last entry.

    Args:
        week_number: Training week number (1-8+)

    Returns:
        Dict with: week, pace_min, pace_max, hr_min, hr_max, notes
    """
    for target in TEMPO_PROGRESSION:
        if target["week"] == week_number:
            return target

    # Default to last progression entry if beyond defined range
    if TEMPO_PROGRESSION:
        last = TEMPO_PROGRESSION[-1].copy()
        last["week"] = week_number
        last["notes"] = "Maintaining peak tempo progression"
        return last

    return {
        "week": week_number,
        "pace_min": "7:45",
        "pace_max": "8:00",
        "hr_min": 175,
        "hr_max": 183,
        "notes": "Peak training phase",
    }


def _plan_file_path(year: int, week: int) -> pathlib.Path:
    """Return the path where a weekly plan should be saved."""
    PLANS_DIR.mkdir(parents=True, exist_ok=True)
    return PLANS_DIR / f"week_plan_{year}_w{week:02d}.txt"


def _today_plan_marker_path() -> pathlib.Path:
    """Return path to a marker file indicating a plan was generated today."""
    PACEIQ_DATA_DIR.mkdir(parents=True, exist_ok=True)
    return PACEIQ_DATA_DIR / f"plan_generated_{date.today().isoformat()}.marker"


def should_generate_plan() -> bool:
    """
    Return True if a new weekly plan should be generated.
    Criteria: it's Monday AND no plan has been generated today.
    """
    today = date.today()
    is_monday = today.weekday() == 0  # Monday = 0

    if not is_monday:
        return False

    marker = _today_plan_marker_path()
    return not marker.exists()


def save_plan_to_file(plan_text: str, week_num: Optional[int] = None, year: Optional[int] = None) -> str:
    """
    Save a weekly plan to disk.

    Saves to:
    1. ~/.paceiq/plans/week_plan_{year}_w{week}.txt
    2. ~/Desktop/paceiq_week_plan.txt (if Desktop exists)
    3. ~/paceiq_week_plan.txt (fallback)

    Returns the primary save path.
    """
    if week_num is None or year is None:
        week_num, year = get_current_week_number()

    # Primary save location
    primary_path = _plan_file_path(year, week_num)
    primary_path.write_text(plan_text, encoding="utf-8")

    # Attempt Desktop save
    desktop = pathlib.Path.home() / "Desktop"
    if desktop.exists() and desktop.is_dir():
        desktop_file = desktop / "paceiq_week_plan.txt"
        try:
            desktop_file.write_text(plan_text, encoding="utf-8")
            print(f"Plan also saved to Desktop: {desktop_file}")
        except IOError as e:
            print(f"Could not save to Desktop: {e}")
    else:
        # Fallback to home directory
        home_file = pathlib.Path.home() / "paceiq_week_plan.txt"
        try:
            home_file.write_text(plan_text, encoding="utf-8")
            print(f"Plan also saved to: {home_file}")
        except IOError as e:
            print(f"Could not save to home directory: {e}")

    # Mark that we generated a plan today
    marker = _today_plan_marker_path()
    marker.write_text(f"Plan generated at {datetime.now().isoformat()}")

    print(f"Weekly plan saved to: {primary_path}")
    return str(primary_path)


def generate_monday_plan(
    db_activities_last_2_weeks: List[Dict[str, Any]],
) -> str:
    """
    Orchestrate generation of a Monday weekly plan using Claude.

    Args:
        db_activities_last_2_weeks: Activity dicts from the last 2 weeks

    Returns:
        Plan text string (generated by the configured LLM provider).
    """
    # Import here to avoid circular imports
    from coach import generate_weekly_plan
    from activity_analyzer import compute_weekly_stats

    week_num, year = get_current_week_number()

    # Split activities into last week vs current week
    last_week_num = week_num - 1 if week_num > 1 else 52
    last_year = year if week_num > 1 else year - 1

    prev_week_activities = [
        a for a in db_activities_last_2_weeks
        if a.get("week_number") == last_week_num and a.get("year") == last_year
    ]

    current_week_activities = [
        a for a in db_activities_last_2_weeks
        if a.get("week_number") == week_num and a.get("year") == year
    ]

    current_week_stats = compute_weekly_stats(current_week_activities)
    current_week_miles = current_week_stats.get("total_miles", 0.0)

    print(f"\nGenerating Week {week_num} training plan...\n")
    plan_text = generate_weekly_plan(
        week_num=week_num,
        prev_week_activities=prev_week_activities,
        current_week_miles=current_week_miles,
    )

    saved_path = save_plan_to_file(plan_text, week_num=week_num, year=year)
    return plan_text


def get_latest_plan() -> Optional[str]:
    """Return the text of the most recently generated plan, or None."""
    if not PLANS_DIR.exists():
        return None

    plan_files = sorted(PLANS_DIR.glob("week_plan_*.txt"), reverse=True)
    if not plan_files:
        return None

    return plan_files[0].read_text(encoding="utf-8")


def format_weekly_schedule_text(week_num: int) -> str:
    """Return a formatted text version of the weekly schedule with this week's targets."""
    tempo_target = get_tempo_target_for_week(week_num)

    lines = [
        f"WEEK {week_num} TRAINING SCHEDULE",
        f"Tempo target: {tempo_target['pace_min']}–{tempo_target['pace_max']}/mi "
        f"at {tempo_target['hr_min']}–{tempo_target['hr_max']} bpm",
        f"Note: {tempo_target['notes']}",
        "",
    ]

    for day, info in WEEKLY_SCHEDULE.items():
        shoe = info.get("shoe", "Adidas Evo SL Woven")
        dist_min = info.get("distance_min", 0)
        dist_max = info.get("distance_max", 0)

        if dist_min == 0 and dist_max == 0:
            dist_str = "Rest"
        elif dist_min == dist_max:
            dist_str = f"{dist_min} mi"
        else:
            dist_str = f"{dist_min}–{dist_max} mi"

        if info.get("type") == "tempo":
            pace_str = f"{tempo_target['pace_min']}–{tempo_target['pace_max']}/mi (tempo)"
        elif info.get("hr_target_max"):
            pace_str = f"easy (HR < {info['hr_target_max']} bpm)"
        else:
            pace_str = "easy effort"

        lines.append(f"{day:10s}: {info['description']}")
        lines.append(f"           Shoe: {shoe} | Distance: {dist_str} | Effort: {pace_str}")
        lines.append("")

    return "\n".join(lines)
